### ISSUE TITLE
player design

### ISSUE THREAD

**Issue by bikko69** [Nukleus73/frogRPG#13]
vi trenger et fungerende konsept som vil bestemme hvordan spiller interacter med items. hvordan skal frosken holde våpen? hvordan skal den plukke opp items?

**Comment by bikko69** [comment]
froskene kan ha våpen i munnen mens de beveger seg, og bruker henda når den angriper. animasjon hvor frosken tar åpnet inn/ut av munnen. typ første attack med sverd er et hvor man "quickdrawer" ut av munnen eller noe liknende. hvis vi klarer å lage enkle animasjoner, trenger ikke åpnet å "sitte fas" i karakteren på noen måte, men kan rett å slett visuelt bare være en animasjon. bare en tanke, kan bli mye jobb i art dept.

**Comment by Daniel-IHansen** [comment]
Flyttet til spilleranimasjoner
