### ISSUE TITLE
Funksjon for multiplayer

### ISSUE THREAD

**Issue by Daniel-IHansen** [Nukleus73/frogRPG#4]
Vi må ha et par funksjoner så de av oss som ikke er kjent med systemet, kan enkelt sende data til serveren. 

Vi trenger en funksjon for å starte en session som returnerer en ID, og en funksjon som sender data til alle maskiner på sessionen (server-side).

Se PeerJS dokumentasjon for mer informasjon: https://peerjs.com/docs/#start

**Comment by Nukleus73** [comment]
Funksjon for oppretting av session, tilkobling, og sending og henting av data. Function createsession, connection & data.

**Comment by Nukleus73** [comment]
// Eksempler på datatyper som kan sendes med Peer:
conn.send({
	strings: 'hi!',
	numbers: 150,
	arrays: [1,2,3],
	evenBinary: new Blob([1,2,3]),
    andMore: {bool: true}
});
